# Site settings
title: Christoffer Holmgren
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Christoffer Holmgren - My personal page, my projects and other random thoughts.
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "http://www.christofferholmgren.se" # the base hostname & protocol for your site
twitter_username: ravengenocide
github_username:  ravengenocide

# Build settings
markdown: kramdown
